project:
  type: website
  output-dir: docs
website:
  title: "Cincinnati Brain Lab Development Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cincibrainlab
      - icon: twitter
        href: https://twitter.com/cbrainlab
format:
  html:
    theme: yeti
    css: styles.css



